import { ThemedScreenshot } from "@/components/themed-screenshot"
import Link from "next/link"
import { InstallBox } from "@/components/install-box"
import { latestRelease, repository, version, vscodeMarketplace } from "@/lib/site"
import accountsLight from "@/public/images/accounts-light.png"
import accountsDark from "@/public/images/accounts-dark.png"

export default function Home() {
  return <main id="main">
    <section className="hero page-width"><div className="hero-copy"><Link href={`/releases#v${version}`} className="release-pill"><span className="status-dot" />Latest: v{version}<span aria-hidden="true">↗</span></Link>
      <p className="eyebrow">YOUR ACCOUNTS. YOUR WORKSPACES.</p><h1>A little order<br />for all your<br /><span>Codex accounts.</span></h1>
      <p className="hero-description">Keep your logins together. Launch separate workspaces with the desktop app, or switch accounts in your current VS Code window.</p>
      <div className="hero-actions"><a className="button primary" href={latestRelease}>Get desktop app <span aria-hidden="true">↓</span></a><a className="text-link" href={vscodeMarketplace}>Get VS Code extension <span aria-hidden="true">↗</span></a></div>
      <p className="platform-line"><span>Linux</span><span>Apple Silicon Mac</span><span>Open source</span></p>
    </div><div className="hero-visual"><div className="visual-label"><span>ONE LAUNCHER, YOUR WHOLE LINEUP</span><span aria-hidden="true">ACCOUNT DASHBOARD</span></div><div className="screenshot-frame"><ThemedScreenshot light={accountsLight} dark={accountsDark} alt="Multi Codex account dashboard showing separate accounts, usage limits and launch buttons for VS Code, Codex and CLI" priority sizes="(max-width: 900px) 100vw, 60vw" /></div><div className="visual-footnote"><span className="small-mark" aria-hidden="true">↳</span>Everything in its own space.<span className="caption-end">Your default login stays yours.</span></div></div></section>
    <section className="feature-strip page-width" aria-label="Features"><div><span className="feature-number">01</span><h2>Accounts stay separate.</h2><p>Each account has its own saved sign-in, conversations and app data.</p></div><div><span className="feature-number">02</span><h2>Launch your way.</h2><p>VS Code, Codex desktop, or CLI in your favorite installed terminal.</p></div><div><span className="feature-number">03</span><h2>Keep an eye on usage.</h2><p>Limits at a glance, with quiet reminders before your usage resets expire.</p></div></section>
    <section className="getting-started page-width"><div><p className="eyebrow">SMALL SETUP. MORE ROOM TO WORK.</p><h2>Up and running<br />in a few minutes.</h2><p>Install the launcher. Add an account. Choose a folder and make it your own.</p><Link className="text-link" href="/docs#first-account">Follow the quick start <span aria-hidden="true">→</span></Link></div><InstallBox /></section>
    <section id="vscode" className="extension-section page-width" aria-labelledby="extension-title"><div><p className="eyebrow">ALREADY IN VS CODE?</p><h2 id="extension-title">Your accounts.<br />The same window.</h2><p>Use your saved desktop accounts inside VS Code, or start with the extension on its own. Choose an account to switch the current Codex panel and check its usage.</p><a className="button primary" href={vscodeMarketplace}>Install from Marketplace <span aria-hidden="true">↗</span></a><p className="extension-platforms">Free pre-release · Linux x64 · macOS 26+ on Intel and Apple Silicon</p></div><div className="extension-steps"><ol><li><span>01</span><div><h3>Install the extension</h3><p>Choose the pre-release of Multi Codex. The official Codex extension is required; the desktop app and Codex CLI are optional.</p></div></li><li><span>02</span><div><h3>Find your saved accounts</h3><p>Open Multi Codex in the activity bar. Existing desktop accounts appear automatically. Use + to add your first account if you’re starting fresh.</p></div></li><li><span>03</span><div><h3>Choose an account</h3><p>Click its row to use it in the current Codex window. Switching is blocked while Codex is working.</p></div></li></ol><Link className="text-link" href="/docs#vscode">Extension setup and compatibility <span aria-hidden="true">→</span></Link></div></section>
    <section className="notes-section page-width"><div><p className="eyebrow">A FEW THOUGHTFUL DETAILS</p><h2>Fits into your day.</h2></div><div className="detail-list"><article><span aria-hidden="true">⌘</span><div><h3>Your terminal, your choice</h3><p>Choose Kitty, Ghostty, Terminal, Konsole and other supported terminals in Launch settings.</p></div></article><article><span aria-hidden="true">◷</span><div><h3>A heads-up before resets expire</h3><p>Available resets expiring within 48 hours appear together. At most twice a day, at least four hours apart.</p></div></article><article><span aria-hidden="true">◐</span><div><h3>Six palettes. Light and dark.</h3><p>Sage, Ocean, Sand, Rose, Plum and Orange. A quieter home for your accounts, whatever the hour.</p></div></article></div></section>
    <section className="source-banner page-width"><div><p className="eyebrow">OPEN SOURCE, THROUGH AND THROUGH</p><h2>Have a look under the hood.</h2></div><a className="button secondary" href={repository}>View on GitHub <span aria-hidden="true">↗</span></a></section>
  </main>
}
