import type { Metadata } from "next"
import Link from "next/link"
import { ThemedScreenshot } from "@/components/themed-screenshot"
import { InstallBox } from "@/components/install-box"
import { latestRelease, repository, vscodeMarketplace } from "@/lib/site"
import workspaceLight from "@/public/images/workspace-light.png"
import workspaceDark from "@/public/images/workspace-dark.png"

export const metadata: Metadata = { title: "Documentation", description: "Install Multi Codex, add accounts, choose a terminal and understand usage reset reminders." }
const sections = [["installation", "Installation"], ["menu-bar", "Mac menu bar"], ["vscode", "VS Code extension"], ["first-account", "Your first account"], ["launching", "Launch a workspace"], ["terminals", "Choose a terminal"], ["reminders", "Reset reminders"], ["updates", "Update the app"], ["troubleshooting", "Troubleshooting"]] as const
export default function Docs() {
  return <main id="main" className="docs-layout page-width"><aside className="docs-sidebar"><p className="eyebrow">THE FIELD GUIDE</p><nav aria-label="Documentation sections">{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav><a className="sidebar-source" href={repository}>Browse the source ↗</a></aside><article className="docs-content">
    <div className="docs-intro"><p className="eyebrow">GET COMFORTABLE</p><h1>A workspace<br />for each account.</h1><p>Everything you need to install Multi Codex and get your accounts working side by side.</p></div>
    <section id="installation"><span className="section-index">01 / INSTALLATION</span><h2>Start with the launcher.</h2><p>Choose your platform below. The installer downloads the latest release, verifies its checksum, and installs the app.</p><InstallBox /><div className="doc-note"><strong>Platform support</strong><p>Linux packages target x86_64: AppImage, DEB and RPM. Mac builds target Apple Silicon on macOS 26 or newer. Windows installers target native x64. The Mac release is unsigned and unnotarized, so the command includes an explicit opt-in.</p><a href="/docs/platform-support">See platform requirements and validation →</a></div><p>Prefer a manual install? Download a package from <a href={latestRelease}>GitHub Releases</a>.</p></section>
    <section id="vscode"><span className="section-index">VS CODE EXTENSION</span><h2>Switch accounts in the window you’re using.</h2><p>Install the free pre-release of <a href={vscodeMarketplace}>Multi Codex from the VS Code Marketplace</a>. It works with the official Codex extension on Linux x64, macOS 26+ on Intel and Apple Silicon, and Windows x64. The desktop app and a separate Codex CLI installation are optional.</p><ol className="doc-steps"><li><strong>Open Multi Codex in the activity bar</strong><p>The extension reads the same local account store as the desktop app. Your saved accounts appear automatically under the same OS user.</p></li><li><strong>Add an account if you’re starting fresh</strong><p>Use + at the top of Accounts to sign in with a browser or import an existing login. Adding an account here also makes it available to the desktop app.</p></li><li><strong>Click the account you want to use</strong><p>The extension connects switching automatically on compatible Codex builds. It keeps the current window and chat open, and blocks switching during observed active work or approvals.</p></li><li><strong>Check all accounts at once</strong><p>Use Check Usage at the top of Accounts to refresh every saved account. Remaining limits and reset times appear beside each name, with progress while checking. Use an account’s usage icon to check just that account. Refresh reads account changes from the desktop app.</p></li></ol><a className="button primary" href={vscodeMarketplace}>Install the pre-release <span aria-hidden="true">↗</span></a><div className="doc-note"><strong>Compatibility</strong><p>This preview uses private Codex integration hooks. Clear queued follow-ups before switching. If a backend is incompatible, the extension shows an error and keeps the window open. Local VS Code is supported; remote SSH, containers, WSL and browser editors are not supported.</p><a href="/docs/extension">Read extension compatibility details →</a></div><p>If saved desktop accounts are missing, check that VS Code runs as the same OS user. For a custom account store, set <strong>Multi Codex: Data Directory</strong> to the desktop app’s account directory and use Refresh.</p></section>
    <section id="menu-bar"><span className="section-index">MAC MENU BAR</span><h2>Your accounts, a click away.</h2><p>Use the Multi Codex icon at the top of your Mac. Pick an account, then choose <strong>Open VS Code</strong>, <strong>Open Codex</strong>, or <strong>Open CLI</strong>. Each submenu shows only installed supported apps. Launching uses the same folder preferences and safety checks as the main window.</p><p><strong>Open Multi Codex</strong> restores the maximized window. <strong>Refresh All Usage</strong> checks every saved account. Closing the window keeps the app in the menu bar; <strong>Quit Multi Codex</strong> fully exits the launcher.</p><p>Quitting Multi Codex leaves separately launched VS Code, Codex and CLI sessions open.</p></section>
    <section id="first-account"><span className="section-index">02 / YOUR FIRST ACCOUNT</span><h2>Add a login of your own.</h2><p>Open Multi Codex, click <strong>Add account</strong>, give it a name, and choose how to connect it:</p><ol className="doc-steps"><li><strong>Sign in with browser</strong><p>Follow the sign-in link and enter the one-time code to connect a ChatGPT account.</p></li><li><strong>Import current</strong><p>Save a copy of your existing Codex login. Your original login stays in place.</p></li><li><strong>Paste JSON</strong><p>Paste an existing Codex <code>auth.json</code> into the desktop app. Keep it private; never paste credentials into a website or GitHub issue.</p></li></ol><p>Accounts appear in plan order: Pro, Plus, Go, then Free. Usage refreshes when the app opens.</p></section>
    <section id="launching"><span className="section-index">03 / LAUNCH A WORKSPACE</span><h2>Pick an account. Pick a folder.</h2><p>Use the account row to launch <strong>VS Code</strong>, the <strong>Codex desktop app</strong>, or <strong>CLI</strong>. Choose a project folder. <strong>Desktop selection is Linux-only</strong> for VS Code and the Codex desktop app on supported desktop environments. On macOS and Windows, the app launches on the current desktop after you choose a folder. CLI launches open in your selected terminal. Set a preferred folder in Launch settings to make the next launch quicker.</p><figure className="doc-figure"><div className="doc-screenshot"><ThemedScreenshot light={workspaceLight} dark={workspaceDark} alt="Multi Codex Linux desktop selection interface" sizes="(max-width: 900px) 100vw, 760px" /></div><figcaption>Linux only · Choose where VS Code or the Codex desktop app opens.</figcaption></figure><p>Each account uses its own saved credentials, conversations and application data. The CLI uses that account’s Codex and SQLite homes.</p><div className="doc-note"><strong>Install your tools first</strong><p>Install the Codex extension inside each isolated VS Code profile. Interactive CLI launches require a complete Codex CLI installation. Standalone launch requires an individually verified Codex desktop build. <Link href="/docs/platform-support">Check supported versions</Link> before installing or updating Codex.</p></div></section>
    <section id="terminals"><span className="section-index">04 / CHOOSE A TERMINAL</span><h2>The terminal you already like.</h2><p>Open <strong>Launch settings → CLI terminal</strong>. Select an installed terminal and save. The choice applies to your next CLI launch.</p><div className="terminal-table"><div><strong>Linux</strong><p>Konsole, GNOME Terminal, XFCE Terminal, xterm, Kitty, Ghostty, Alacritty, Foot</p></div><div><strong>macOS</strong><p>Terminal, Kitty, Ghostty, Alacritty</p></div><div><strong>Windows</strong><p>Windows Terminal, PowerShell</p></div></div><p><strong>Automatic</strong> uses the first supported terminal found. The dropdown shows Automatic and installed terminals only. If a chosen terminal is later removed, the app asks you to select another.</p><p>You can set the full path to your Codex executable in the Advanced section. Use an executable path without quotes or extra arguments.</p></section>
    <section id="reminders"><span className="section-index">05 / RESET REMINDERS</span><h2>A quiet heads-up.</h2><p>When available usage resets expire within <strong>48 hours</strong>, a small reminder appears at the top of the app. Multiple resets across accounts are grouped into one popup.</p><ul className="doc-bullets"><li>At most <strong>two reminders per local calendar day</strong>.</li><li>At least <strong>four hours between reminders</strong>, including across midnight.</li><li>The limit is saved across app restarts.</li><li>Expired, used, undated or stale reset details do not trigger a reminder.</li></ul><p>Click <strong>View resets</strong> to see the accounts, then open an account for exact expiry details. Dismiss the popup with ×. It also closes after a minute when you are not interacting with it. The app checks fresh usage periodically while running. On Mac, closing the window keeps the menu-bar app running; Quit exits it.</p></section>
    <section id="updates"><span className="section-index">06 / UPDATE THE APP</span><h2>Fresh app. Familiar accounts.</h2><p>Close Multi Codex, then run the update command for your platform. The updater verifies the download before replacing the application and preserves saved accounts and profile data.</p><InstallBox update /><p>For an update without reopening the app, add <code>MULTI_CODEX_NO_LAUNCH=1</code> before <code>bash</code> on Linux/Mac, or add <code>-NoLaunch</code> to the Windows command. Keep a backup of important local data as part of your normal workflow.</p></section>
    <section id="troubleshooting"><span className="section-index">07 / TROUBLESHOOTING</span><h2>A few common questions.</h2><details open><summary>The CLI closes immediately or says it has no complete local package.</summary><p>A VS Code extension helper can be discovered in your PATH even though it cannot start the interactive CLI. Install the full <a href="https://learn.chatgpt.com/docs/codex/cli">official Codex CLI</a>, then select its executable in Launch settings. Multi Codex skips known extension helpers for interactive launches.</p></details><details><summary>Why does the CLI ask me to sign in?</summary><p>Launch CLI from the saved account’s row to use that account’s sign-in. Running <code>codex</code> separately in a terminal uses its default home instead. If an account’s credentials have expired or been revoked, reconnect that account in Multi Codex.</p></details><details><summary>macOS blocks the first open.</summary><p>This release is unsigned. After attempting to open it, go to System Settings → Privacy & Security → Open Anyway and confirm Open. See <a href="https://support.apple.com/en-us/102445">Apple’s first-open instructions</a>. Do not disable Gatekeeper.</p></details><details><summary>Why is my terminal missing?</summary><p>Only installed supported terminals appear in the dropdown. Install your terminal, reopen Launch settings, and select it. If your saved terminal has been removed, its selection shows a warning until you choose an installed replacement. On Mac, install supported apps in Applications or your user’s Applications folder.</p></details><details><summary>I do not see a reset reminder.</summary><p>The reminder needs fresh usage details containing available reset credits with a known expiry within 48 hours. It will also wait if you have already seen two today or the last reminder was less than four hours ago. Use an account’s Refresh button to check current details.</p></details><p className="docs-end">Still stuck? <Link href="/issues">Report an issue →</Link> with the error and platform details. Leave out credentials and personal conversation data.</p></section>
  </article></main>
}
