import { test, expect, type Page } from "@playwright/test"
async function fillReport(page: Page) {
  await page.getByLabel("A short title").fill("CLI closes immediately")
  await page.getByRole("combobox", { name: "Platform" }).selectOption("Linux")
  await page.getByLabel("App version").fill("1.3.8")
  await page.getByLabel("What happened?").fill("The terminal closes immediately after launch.")
  await page.getByLabel("Steps to reproduce").fill("1. Open the app. 2. Launch CLI.")
  await page.getByLabel("What did you expect?").fill("The terminal stays open.")
  await page.getByRole("checkbox").check()
}
test("issue form submits once and displays the GitHub link in the selected theme", async ({ page }) => {
  let submissions = 0
  await page.route("**/api/issues", async route => { submissions++; expect(route.request().postDataJSON()).toMatchObject({ title: "CLI closes immediately", platform: "Linux", publicConsent: true, website: "" }); await route.fulfill({ status: 201, contentType: "application/json", body: JSON.stringify({ number: 42, url: "https://github.com/wrestle-R/multi-codex/issues/42" }) }) })
  await page.goto("/docs")
  await page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Report an issue" }).click()
  await expect(page.getByRole("heading", { level: 1, name: "Something out of place?" })).toBeVisible()
  await page.getByRole("button", { name: "Toggle color theme" }).click()
  await fillReport(page)
  await page.getByRole("button", { name: "Submit issue", exact: true }).click()
  await expect(page.getByRole("heading", { name: /Issue #42 is on GitHub/ })).toBeVisible()
  await expect(page.getByRole("link", { name: "View your issue" })).toHaveAttribute("href", "https://github.com/wrestle-R/multi-codex/issues/42")
  await expect(page.getByRole("status")).toBeFocused()
  expect(submissions).toBe(1)
  await page.getByRole("button", { name: "Report another issue" }).click()
  await expect(page.getByLabel("A short title")).toHaveValue("")
  await expect(page.getByRole("checkbox")).not.toBeChecked()
  await page.setViewportSize({ width: 320, height: 700 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
})
test("failed submissions keep report text and a filled-in GitHub fallback", async ({ page }) => {
  await page.route("**/api/issues", route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Direct submission is temporarily unavailable." }) }))
  await page.goto("/issues")
  await fillReport(page)
  await page.getByRole("button", { name: "Submit issue", exact: true }).click()
  await expect(page.getByRole("form", { name: "Report an issue" }).getByRole("alert")).toContainText("Direct submission is temporarily unavailable.")
  await expect(page.getByLabel("What happened?")).toHaveValue("The terminal closes immediately after launch.")
  const url = new URL((await page.getByRole("link", { name: "Open on GitHub instead" }).getAttribute("href"))!)
  expect(url.origin + url.pathname).toBe("https://github.com/wrestle-R/multi-codex/issues/new")
  expect(url.searchParams.get("title")).toBe("CLI closes immediately")
  expect(url.searchParams.get("body")).toContain("Steps to reproduce")
  await expect(page.getByRole("button", { name: "Submit issue", exact: true })).toBeEnabled()
})
test("empty reports cannot submit and pending submissions disable editing and repeat clicks", async ({ page }) => {
  let submissions = 0
  let release: () => void = () => {}
  const pending = new Promise<void>(resolve => { release = resolve })
  await page.route("**/api/issues", async route => { submissions++; await pending; await route.fulfill({ status: 502, contentType: "application/json", body: JSON.stringify({ error: "GitHub could not accept the report." }) }) })
  await page.goto("/issues")
  await page.getByRole("button", { name: "Submit issue", exact: true }).click()
  expect(submissions).toBe(0)
  await fillReport(page)
  await page.getByRole("button", { name: "Submit issue", exact: true }).click()
  await expect(page.getByRole("button", { name: "Submitting…" })).toBeDisabled()
  await expect(page.getByLabel("A short title")).toBeDisabled()
  await expect.poll(() => submissions).toBe(1)
  release()
  await expect(page.getByRole("form", { name: "Report an issue" }).getByRole("alert")).toContainText("GitHub could not accept")
})
