import { test, expect } from "@playwright/test"

test("docs explain Linux-only desktop placement and show screenshots matching a persistent theme", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.emulateMedia({ colorScheme: "light" })
  await page.goto("/docs#launching")
  await expect(page.locator("#launching")).toContainText("Desktop selection is Linux-only")
  await expect(page.locator("#launching")).toContainText("On macOS, the app launches after you choose a folder.")
  await expect(page.locator("#terminals")).toContainText("installed terminals only")
  const screenshot = page.getByRole("img", { name: "Multi Codex Linux desktop selection interface" })
  await expect(screenshot).toHaveAttribute("src", /workspace-light/)
  await expect.poll(() => screenshot.evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  const toggle = page.getByRole("button", { name: "Toggle color theme" })
  await toggle.focus()
  await page.keyboard.press("Enter")
  await expect(toggle).toHaveAttribute("aria-pressed", "true")
  await expect(screenshot).toHaveAttribute("src", /workspace-dark/)
  await expect.poll(() => screenshot.evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  expect(await page.locator("body").evaluate(element => getComputedStyle(element).backgroundColor)).toBe("rgb(24, 27, 24)")
  await page.reload()
  await expect(toggle).toHaveAttribute("aria-pressed", "true")
  await page.emulateMedia({ colorScheme: "dark" })
  await page.emulateMedia({ colorScheme: "light" })
  await expect(toggle).toHaveAttribute("aria-pressed", "true")
  await page.getByRole("link", { name: "Multi Codex home" }).click()
  await expect(page.getByRole("img", { name: /account dashboard/ })).toHaveAttribute("src", /accounts-dark/)
  await toggle.click()
  await expect(page.getByRole("img", { name: /account dashboard/ })).toHaveAttribute("src", /accounts-light/)
  await page.getByRole("link", { name: "Changelog", exact: true }).click()
  await expect(toggle).toHaveAttribute("aria-pressed", "false")
  await page.setViewportSize({ width: 320, height: 700 })
  await page.goto("/docs")
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
  await toggle.click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
  expect(errors).toEqual([])
})

test("new visitors follow system theme changes until choosing their own theme", async ({ page }) => {
  await page.emulateMedia({ colorScheme: "dark" })
  await page.goto("/docs")
  const toggle = page.getByRole("button", { name: "Toggle color theme" })
  await expect(toggle).toHaveAttribute("aria-pressed", "true")
  await page.emulateMedia({ colorScheme: "light" })
  await expect(toggle).toHaveAttribute("aria-pressed", "false")
  await toggle.click()
  await page.emulateMedia({ colorScheme: "dark" })
  await page.emulateMedia({ colorScheme: "light" })
  await expect(toggle).toHaveAttribute("aria-pressed", "true")
})

test("theme selection remains usable when browser storage is unavailable", async ({ page }) => {
  await page.addInitScript(() => {
    Storage.prototype.getItem = () => { throw new Error("Storage blocked") }
    Storage.prototype.setItem = () => { throw new Error("Storage blocked") }
  })
  await page.emulateMedia({ colorScheme: "light" })
  await page.goto("/docs")
  const toggle = page.getByRole("button", { name: "Toggle color theme" })
  await expect(toggle).toHaveAttribute("aria-pressed", "false")
  await toggle.click()
  await expect(toggle).toHaveAttribute("aria-pressed", "true")
  await page.getByRole("link", { name: "Changelog", exact: true }).click()
  await expect(toggle).toHaveAttribute("aria-pressed", "true")
})
